@include('partials.fields.text', ['name' => 'Name', 'field' => 'name', 'value' => $name ?? null,])
@include('partials.fields.text', ['name' => 'Numeric Code', 'field' => 'numeric_code', 'value' => $numeric_code ?? null,])
@include('partials.fields.text', ['name' => 'Alpha Code', 'field' => 'alpha_code', 'value' => $alpha_code ?? null,])
@include('partials.fields.text', ['name' => 'Dialing Code', 'field' => 'dialing_code', 'value' => $dialing_code ?? null,])
@include('partials.fields.submit')
